Repository React-Bootcamp-WoMarkersCode/cv-speed-hiring, pull requests merged in 2020-04, with the labels that each got.

#44 Feature/configurando jest
  package-lock.json
  package.json
  src/setupTests.js
Labels: test

#53 Componente de página NotFound
  package-lock.json
  src/assets/img/notfound.png
  src/components/NotFoundContainer/index.js
  src/components/NotFoundContainer/style.css
  src/pages/NotFound/index.js
  src/pages/NotFound/style.css
Labels: componente, not-found

#65 Funcionalidade de filtrar lista de evento
  src/components/Search/SearchEvento.js
  src/components/Search/SearchEvento/style.css
  src/pages/Home/index.js
Labels: funcionalidade, home

#71 Formulário de Cadastro de Usuário
  package.json
  src/components/Forms/UserForm.js
  src/components/Forms/UserForm/style.css
  src/pages/CadastroConta/index.js
  yarn.lock
Labels: cadastroUsuario, componente

#73 Validação do form de Cadastro de Usuário
  package.json
  src/components/Forms/UserForm.js
  src/components/Forms/UserForm/style.css
  src/pages/CadastroConta/index.js
  yarn.lock
Labels: cadastroUsuario, funcionalidade

#83 Feature/cadastro de participantes
  package.json
  src/Routes.js
  src/assets/img/woman.jpg
  src/components/AccessCode/AccessCode.js
  src/components/Curriculo/FormInput.js
  src/components/Form/FormCheckbox.js
  src/components/Form/FormDate.js
  src/components/Form/FormFile.js
  src/components/Form/FormInput.js
  src/components/ImageUpload/index.js
  src/components/ImageUpload/styles.css
  src/pages/CadastroParticipante/Avatar.js
  src/pages/CadastroParticipante/DadosPessoais.js
  src/pages/CadastroParticipante/ExperienciaAcademica.js
  src/pages/CadastroParticipante/ExperienciaProfissional.js
  src/pages/CadastroParticipante/index.js
  src/pages/CadastroParticipante/style.css
  src/pages/Home/index.js
Labels: cadastroParticipante, componente

#85 feature/sobre
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/Routes.js
  src/Routes.test.js
  src/assets/img/woman-dev.jpg
  src/assets/img/workshop.jpg
  src/components/Footers/DemoFooter.js
  src/components/Navbars/IndexNavbar.js
  src/components/NotFoundContainer/index.js
  src/pages/PoliticaPrivacidade/index.js
  src/pages/Sobre/index.js
  src/pages/TermoUso/index.js
Labels: componente, sobre

#86 Inclusão do link de cadastro de participante
  src/Routes.js
Labels: bug

#87 Funcionalidade de salvar cadastro de usuário
  package.json
  src/components/Forms/UserForm.js
  src/pages/CadastroConta/index.deprecated.js
  src/pages/CadastroConta/index.js
  src/services/FirebaseService.js
  src/utils/firebaseUtils.js
  yarn.lock
Labels: cadastroUsuario, funcionalidade

#89 Componente de Form Login
  src/components/Forms/LoginForm.js
  src/components/Forms/LoginForm/style.css
  src/pages/AcessoConta/index.js
Labels: componente, login

#90 Alteração na visualização da mensagem de cadastro concluido do participante
  src/pages/CadastroParticipante/index.js
Labels: cadastroParticipante

#98 Página de Cadastro de Evento com Validações
  .gitignore
  package-lock.json
  src/components/Forms/EventoForm.js
  src/components/Forms/EventoForm/style.css
  src/components/Forms/LoginForm/style.css
  src/components/Forms/UserForm/style.css
  src/components/Navbars/IndexNavbar.js
  src/pages/CadastroEvento/index.js
Labels: cadastroEvento, componente, melhoria

#107 feature - loading de carregamento nas chamadas da API
  package.json
  src/Routes.js
  src/assets/json/quotesloading.json
  src/components/Cards/CardParticipante/ListaCardParticipante.js
  src/components/Headers/LandingPageHeader.js
  src/components/Loading/index.js
  src/components/Search/SearchEvento.js
  src/hooks/useData.js
Labels: melhoria

#106 Ajuste no layout do login
  src/components/Forms/LoginForm.js
  src/components/Forms/LoginForm/style.css
Labels: melhoria

#108 Aplicação de layout e identidade visual na page de cadastro
  package-lock.json
  src/components/Curriculo/style.css
  src/components/Footers/DemoFooter.js
  src/components/Footers/style.css
  src/components/Forms/LoginForm.js
  src/components/Forms/LoginForm/style.css
  src/components/Forms/UserForm.js
  src/components/Forms/UserForm/style.css
  src/index.js
  yarn.lock
Labels: melhoria

#111 Componente Upload CSV cadastro de participantes
  package.json
  src/assets/img/file-plus.png
  src/pages/Overview/OverviewParticipantes/index.js
  src/pages/Overview/OverviewParticipantes/styles.css
Labels: cadastroParticipante

#114 Cadastro de Eventos
  src/components/Cards/CardEvento/index.js
  src/components/Forms/EventoForm.js
  src/components/Forms/EventoForm/style.css
  src/components/Forms/UserForm.js
  src/pages/Evento/index.js
  src/pages/Home/index.js
  src/pages/Overview/OverviewEventos/index.js
  src/pages/Overview/OverviewParticipantes/index.js
  src/services/FirebaseService.js
  yarn.lock
Labels: cadastroEvento, funcionalidade, melhoria
